version: "3.8"
services:

  cinema-reservation-router:
    image: docker-registry.theliver.pl/cinema-reservation-router:latest
    container_name: cinema-reservation-router
    restart: always
    ports:
      - 7878:80

  cinema-reservation-frontend:
    image: docker-registry.theliver.pl/cinema-reservation-frontend:latest
    container_name: cinema-reservation-frontend
    ports:
      - 7777:80
    restart: always

  cinema-reservation-backend:
    image: docker-registry.theliver.pl/cinema-reservation-backend:latest
    container_name: cinema-reservation-backend
    ports:
      - 7778:8080
    restart: always
