# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: App router CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: cinema-reservation-router
  DOCKER_REGISTRY: docker-registry.theliver.pl

jobs:
  build_and_push:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build cinema-router --file cinema-router/Dockerfile --tag $IMAGE_NAME

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.THELIVER_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.THELIVER_DOCKER_REGISTRY_PASSWORD }}
          registry: docker-registry.theliver.pl

      - name: Push image :latest
        run: |
          IMAGE_ID=docker-registry.theliver.pl/$IMAGE_NAME
          VERSION=latest
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION